name: Build
on:
  push:

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: iws-rs
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build
